---
title: "Hurricane Tracking"
author: "John Mernitz"
date: "2024-12-13"
output: html_document
---

```{r setup, include=FALSE}
library(sf)
library(tidyverse)
library(ggmap)
library(spData)
library(lubridate)
data(world)
data(us_states)
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
dataurl="https://www.ncei.noaa.gov/data/international-best-track-archive-for-climate-stewardship-ibtracs/v04r01/access/csv/ibtracs.NA.list.v04r01.csv"
storm_data <- read_csv(dataurl)

```


```{r}
storm_data <- storm_data %>%
  mutate(year = year(ISO_TIME))

# Filter data 1950 >> present
storm_data <- storm_data %>%
  filter(year >= 1950)

# Convert -999.0 to NA in numeric columns
storm_data <- storm_data %>%
  mutate_if(is.numeric, function(x) ifelse(x == -999.0, NA, x))

# Add col for decade
storm_data <- storm_data %>%
  mutate(decade = (floor(year / 10) * 10))

storms <- st_as_sf(storm_data, coords = c("LON", "LAT"), crs = 4326)

region <- st_bbox(storms)
```


```{r}
ggplot() +
  geom_sf(data = world) +
  facet_wrap(~decade) +
  stat_bin2d(data = storms, aes(y = st_coordinates(storms)[,2], x = st_coordinates(storms)[,1]), bins = 100) +
  scale_fill_distiller(palette = "YlOrRd", trans = "log", direction = -1, breaks = c(1, 10, 100, 1000)) +
  coord_sf(ylim = region[c(2,4)], xlim = region[c(1,3)]) +
  theme_minimal() +
  labs(title = "Storms by Decade")
```


```{r}
states <- st_transform(us_states, st_crs(storms))

states <- states %>%
  select(state = NAME)

# spatial join to find states w/ storms
storm_states <- st_join(storms, states, join = st_intersects, left = FALSE)

# Group by state, summarize the num unique storms
state_storms <- storm_states %>%
  group_by(state) %>%
  summarize(storms = length(unique(NAME))) %>%
  arrange(desc(storms)) %>%
  slice(1:5)

state_storms
```

